### ISSUE TITLE
好多图片都挂了

### ISSUE THREAD

**Issue by fanshaohua-fan** [jackpgao/jackpgao.github.io#1]
例如：
http://jackpgao.github.io/2018/05/22/ClickHouse-Data-Replication/

你还在维护博客不？有时间看看？

**Comment by jackpgao** [comment]
图在7牛，7牛把测试域名给下了。手里没有带备案的域名，挂不上图。

**Comment by fanshaohua-fan** [comment]
Github Page本身就可以用作图床

**Comment by jackpgao** [comment]
本地写博客，一键上7牛比较容易。

这个PPT可以发你，留个邮箱。

**Comment by fanshaohua-fan** [comment]
好的，那谢谢啦^_^
fanshaohua.fan(At)gmail.com

jackpgao <notifications@github.com> 于 2019年4月10日周三 上午11:46写道：
